name: Kernel Module CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
      options: --privileged  # Required for kernel module operations

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup environment
      run: |
        # Install dependencies
        apt-get update
        apt-get install -y --no-install-recommends \
          build-essential \
          libelf-dev \
          kmod \
          git \
          qemu-system-x86 \
          gcc-aarch64-linux-gnu \
          libc6-dev-arm64-cross \
          wget
          
        # Verify kernel headers
        if [ ! -d "/lib/modules/*/build" ]; then
          echo "❌ Kernel headers not found for $(uname -r)"
          exit 1
        fi

    - name: Build module
      run: |
        make

    - name: Run smoke tests
      run: |
        # Simple module load/unload test
        insmod your_module.ko
        dmesg | grep "kvm_probe_drv:"
        rmmod kvm_probe_drv.ko
        
        # Verify error logs are captured
        if dmesg | grep -q "your_module:.*ERR"; then
          echo "❌ Error logs detected in dmesg"
          exit 1
        fi

    - name: Cross-compile for ARM64
      run: |
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- \
          -C /lib/modules/$(uname -r)/build M=$PWD modules
        file your_module.ko

    - name: Archive debug artifacts
      if: ${{ failure() }}
      run: |
        dmesg > dmesg.log
        cat dmesg.log
